# Generated by Django 4.0.4 on 2022-06-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=3)),
                ('Brgy', models.CharField(max_length=50)),
                ('Contact_No', models.CharField(max_length=20)),
                ('ZipCode', models.CharField(max_length=30)),
                ('DSWD_id', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='employee_branch',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='msystem.member_info'),
        ),
        migrations.AlterField(
            model_name='company_report',
            name='employee_comrep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='msystem.member_info'),
        ),
        migrations.AlterField(
            model_name='employee_report',
            name='employee_emrep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='msystem.member_info'),
        ),
        migrations.AlterField(
            model_name='employee_salary',
            name='employee_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='msystem.member_info'),
        ),
        migrations.DeleteModel(
            name='Employee_info',
        ),
    ]
