# Generated by Django 4.0.4 on 2022-06-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0003_rename_position_branch_program_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_Salary',
            new_name='Cash_Assistance',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='Company_branch',
            new_name='Barangay_branch',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='employee_branch',
            new_name='member_branch',
        ),
        migrations.RenameField(
            model_name='company_report',
            old_name='employee_comrep',
            new_name='employee_employee_infocomrep',
        ),
    ]
