# Generated by Django 4.0.4 on 2022-06-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0004_rename_employee_salary_cash_assistance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Muncipality',
            new_name='Municipality',
        ),
    ]
