# Generated by Django 4.0.4 on 2022-06-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0006_rename_municipality_branch_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Department',
            new_name='Municipality',
        ),
    ]
