# Generated by Django 4.0.4 on 2022-06-29 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0007_rename_department_branch_municipality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barangayreport', models.TextField(default='')),
                ('Barangay_comment', models.TextField(default='')),
                ('Memreport_date', models.DateTimeField(default='')),
                ('Member_infocomrep', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='msystem.member_info')),
            ],
        ),
        migrations.CreateModel(
            name='Member_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Memberreport', models.TextField(default='')),
                ('Membercomment', models.TextField(default='')),
                ('Program_hours', models.TextField(default='')),
                ('Memreport_date', models.DateTimeField(default='')),
                ('Memrep', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='msystem.member_info')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cash_Assistance',
            new_name='Program',
        ),
        migrations.RemoveField(
            model_name='employee_report',
            name='employee_emrep',
        ),
        migrations.AlterField(
            model_name='branch',
            name='Barangay_branch',
            field=models.CharField(choices=[('Cavite', 'cavite'), ('Manila', 'manila'), ('Batangas', 'batangas')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='Municipality',
            field=models.CharField(choices=[('Dasma', 'Dasma'), ('Lobo', 'Lobo'), ('Pasay', 'Pasay')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Company_report',
        ),
        migrations.DeleteModel(
            name='Employee_report',
        ),
    ]
