# Generated by Django 4.0.4 on 2022-06-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0008_barangay_report_member_report_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangay_report',
            old_name='Barangay_comment',
            new_name='Barangay_suggestions',
        ),
        migrations.RenameField(
            model_name='barangay_report',
            old_name='Memreport_date',
            new_name='Barangayport_date',
        ),
        migrations.RenameField(
            model_name='barangay_report',
            old_name='Member_infocomrep',
            new_name='Member_rep',
        ),
        migrations.RenameField(
            model_name='member_report',
            old_name='Memrep',
            new_name='Membe_report',
        ),
        migrations.RenameField(
            model_name='member_report',
            old_name='Memberreport',
            new_name='Membereport',
        ),
        migrations.RenameField(
            model_name='member_report',
            old_name='Program_hours',
            new_name='Memberrate',
        ),
        migrations.RenameField(
            model_name='member_report',
            old_name='Memreport_date',
            new_name='Memberrep_date',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='Offense',
            new_name='Months',
        ),
    ]
