# Generated by Django 4.0.4 on 2022-06-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0009_rename_barangay_comment_barangay_report_barangay_suggestions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='Rate',
            new_name='Capital',
        ),
        migrations.RemoveField(
            model_name='program',
            name='Total',
        ),
    ]
