# Generated by Django 4.0.4 on 2022-06-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0010_rename_rate_program_capital_remove_program_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='Capital',
            new_name='Rate',
        ),
        migrations.AddField(
            model_name='program',
            name='Total',
            field=models.TextField(default=''),
        ),
    ]
