# Generated by Django 4.0.4 on 2022-07-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0011_rename_capital_program_rate_program_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='member_info',
            new_name='employee_info',
        ),
    ]
