# Generated by Django 4.0.4 on 2022-07-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msystem', '0012_rename_member_info_program_employee_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='employee_info',
            new_name='member_info',
        ),
    ]
